queue_rules:
  - name: default
    merge_conditions:
      - "-draft"
    merge_method: merge
    update_method: rebase

pull_request_rules:
  - name: Label Scala Steward and Renovate PRs with 'build'
    conditions:
      - or:
          - "author=scala-steward"
          - "author=slick-scala-steward[bot]"
          - "author=renovate[bot]"
    actions:
      label:
        add:
          - build

  - name: Automatic merge on approval
    conditions:
      - "check-success=Build and Test (javaMin, 2.12.x)"
      - "check-success=Build and Test (javaMin, 2.13.x)"
      - "check-success=Build and Test (javaMin, 3.x)"
      - "check-success=Build and Test (javaLatest, 2.12.x)"
      - "check-success=Build and Test (javaLatest, 2.13.x)"
      - "check-success=Build and Test (javaLatest, 3.x)"
      - "check-success=Check conformance with version policy (2.12.x)"
      - "check-success=Check conformance with version policy (2.13.x)"
      - "check-success=Check conformance with version policy (3.x)"
      - "#changes-requested-reviews-by=0"
      - or:
          - "#approved-reviews-by>=1"
          - "author=nafg"
          - "author=scala-steward"
          - "author=slick-scala-steward[bot]"
          - "author=renovate[bot]"
    actions:
      queue:
        name: default
